<?php
/**
 * @file
 * The main module file.
 */

use Drupal\member_login\UserAgent;
 /**
 * Implements hook_user_login().
 */

function member_login_user_login($account) {
  $u_agent = $_SERVER['HTTP_USER_AGENT'];
  $user_agent = new UserAgent($u_agent);
  $browser = $user_agent->getBrowser();

  $keys = [
    'mlid' => null,
  ];
  $fields = [
    'uid' => $account->id(),
    'date' => time(),
    'username'=> $account->getDisplayName(),
    'browser_name' => $browser['name'],
    'browser_version' => $browser['version'],
    'browser_platform' => $browser['platform'],
  ];

  \Drupal::database()->merge('member_login')
    ->key($keys)
    ->fields($fields)
    ->execute();
}

